// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonLinks: typeof import('./src/components/common/links.vue')['default']
    DappBoard: typeof import('./src/components/dapp/board.vue')['default']
    DappConnectButton: typeof import('./src/components/dapp/connect-button.vue')['default']
    DappLoader: typeof import('./src/components/dapp/loader.vue')['default']
    DappLogoCoinbaseWallet: typeof import('./src/components/dapp/logo/coinbase-wallet.vue')['default']
    DappLogoMetaMask: typeof import('./src/components/dapp/logo/meta-mask.vue')['default']
    DappLogoWalletConnect: typeof import('./src/components/dapp/logo/WalletConnect.vue')['default']
    DappModal: typeof import('./src/components/dapp/modal.vue')['default']
    MainFooter: typeof import('./src/components/main/footer.vue')['default']
    MainHeader: typeof import('./src/components/main/header.vue')['default']
    RoadmapAccordion: typeof import('./src/components/roadmap/accordion.vue')['default']
    RoadmapSlider: typeof import('./src/components/roadmap/slider.vue')['default']
    RoadmapTabs: typeof import('./src/components/roadmap/tabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionFeatures: typeof import('./src/components/section/features.vue')['default']
    SectionHero: typeof import('./src/components/section/hero.vue')['default']
    SectionLegacy: typeof import('./src/components/section/legacy.vue')['default']
    SectionPartners: typeof import('./src/components/section/partners.vue')['default']
    SectionRoadmap: typeof import('./src/components/section/roadmap.vue')['default']
    SectionVault: typeof import('./src/components/section/vault.vue')['default']
    SectionVaultFeatures: typeof import('./src/components/section/vault-features.vue')['default']
    SectionWelcome: typeof import('./src/components/section/welcome.vue')['default']
  }
}

export {}
